# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: GG
author:
  name: Ganesh Gunasegaran
  email: me@itsgg.com

description: >-
  The Architect

copyright: >-
  Â© Ganesh Gunasegaran

show_excerpts: true

header_pages:
  - profile.md
  - about.md

minima:
  skin: dark
  social_links:
    - { platform: github,  user_url: "https://github.com/itsgg" }
    - { platform: twitter, user_url: "https://twitter.com/itsgg" }
    - { platform: youtube, user_url: "https://www.youtube.com/@itsgg.youtube" }
    - { platform: facebook, user_url: "https://www.facebook.com/itsgg.fb" }
    - { platform: instagram, user_url: "https://www.instagram.com/itsgg.insta" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/itsgg" }

# Build settings
markdown: kramdown
remote_theme: jekyll/minima
feed:
  path: /blog/feed.atom
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true
  
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
