# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: GG

url: https://itsgg.com
lang: en

author:
  name: Ganesh Gunasegaran
  nickname: GG
  email: me@itsgg.com

description: >-
  The Architect

google_analytics: G-ER412RRHJF

header_pages:
  - books.md
  - about.md

minima:
  skin: dark
  show_excerpts: true
  social_links:
    - { title: linkedin, url: "https://www.linkedin.com/in/itsgg", icon: linkedin }
    - { title: twitter, url: "https://twitter.com/itsgg", icon: x-twitter }
    - { title: github, url: "https://github.com/itsgg", icon: github }
    - { title: rss, url: "/blog/feed.atom", icon: stack-exchange }
  
paginate: 10
paginate_path: "/page/:num/"

timezone: Asia/Kolkata

markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true

remote_theme: jekyll/minima

feed:
  path: /blog/feed.atom

plugins:
  - jekyll-compose
  - jekyll-feed
  - jekyll-gfm-admonitions
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

permalink: /blog/:year/:month/:day/:title/
